// src/components/Input.vue
<template>
  <div class="input-group">
    <label v-if="label" :for="id" class="label">{{ label }}</label>
    <input
      :id="id"
      :type="type"
      :placeholder="placeholder"
      :value="modelValue"
      @input="$emit('update:modelValue', $event.target.value)"
      class="input"
    />
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  label: String,
  type: { type: String, default: 'text' },
  placeholder: String,
  modelValue: String,
})

defineEmits(['update:modelValue'])

const id = computed(() => `input-${Math.random().toString(36).substr(2, 9)}`)
</script>

<style scoped>
.input-group {
  display: flex;
  flex-direction: column;
}

.label {
  font-family: var(--font-sans);
  font-size: 0.875rem;
  font-weight: 600;
  color: var(--text-strong);
  margin-bottom: 8px;
}

.input {
  padding: 12px 14px;
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  font-family: var(--font-sans);
  font-size: 1rem;
  color: var(--text-body);
  background: var(--white);
  transition: border-color var(--dur-fast) var(--ease-soft), box-shadow var(--dur-fast) var(--ease-soft);
}

.input:focus {
  outline: none;
  border-color: var(--brand);
  box-shadow: 0 0 0 3px var(--focus-ring-soft);
}

.input::placeholder {
  color: var(--text-muted);
}
</style>

// design-system/ashish-portfolio-design-system/project/components/forms/Input.jsx
import React from "react";

/**
 * Input — soft rounded text field with optional label & hint.
 */
export function Input({ label = "", hint = "", error = "", id, style = {}, ...rest }) {
  const inputId = id || (label ? label.toLowerCase().replace(/\s+/g, "-") : undefined);
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "6px", ...style }}>
      {label && (
        <label
          htmlFor={inputId}
          style={{
            fontFamily: "var(--font-sans)",
            fontSize: "0.8125rem",
            fontWeight: 600,
            color: "var(--text-strong)",
          }}
        >
          {label}
        </label>
      )}
      <input
        id={inputId}
        style={{
          fontFamily: "var(--font-sans)",
          fontSize: "1rem",
          color: "var(--text-strong)",
          padding: "12px 16px",
          background: "var(--surface-card)",
          border: `1.5px solid ${error ? "var(--heart)" : "var(--border)"}`,
          borderRadius: "var(--radius-md)",
          outline: "none",
          transition: "border-color var(--dur-fast) var(--ease-soft), box-shadow var(--dur-fast) var(--ease-soft)",
          width: "100%",
        }}
        onFocus={(e) => {
          e.currentTarget.style.borderColor = "var(--peri-400)";
          e.currentTarget.style.boxShadow = "0 0 0 3px var(--peri-100)";
        }}
        onBlur={(e) => {
          e.currentTarget.style.borderColor = error ? "var(--heart)" : "var(--border)";
          e.currentTarget.style.boxShadow = "none";
        }}
        {...rest}
      />
      {(hint || error) && (
        <span
          style={{
            fontSize: "0.75rem",
            color: error ? "var(--heart)" : "var(--text-muted)",
          }}
        >
          {error || hint}
        </span>
      )}
    </div>
  );
}
