// src/components/Button.vue
<template>
  <component
    :is="tag"
    :class="['button', `variant-${variant}`, `size-${size}`, { full }]"
    v-bind="{ ...attrs, href: href }"
  >
    <slot></slot>
  </component>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  variant: { type: String, default: 'primary' }, // primary, secondary, outline, ghost, ink
  size: { type: String, default: 'md' }, // sm, md, lg
  full: { type: Boolean, default: false },
  as: { type: String, default: 'button' },
  href: String,
})

const attrs = computed(() => {
  if (props.as === 'a') {
    return { href: props.href }
  }
  return { type: 'button' }
})

const tag = computed(() => {
  if (props.as === 'a') return 'a'
  return 'button'
})
</script>

<style scoped>
.button {
  font-family: var(--font-sans);
  font-weight: 600;
  border-radius: var(--radius-pill);
  border: none;
  cursor: pointer;
  transition: all var(--dur-fast) var(--ease-soft);
  text-decoration: none;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  white-space: nowrap;
}

.button:active {
  transform: scale(0.97);
}

/* Sizes */
.size-sm {
  font-size: 0.875rem;
  padding: 8px 16px;
}

.size-md {
  font-size: 1rem;
  padding: 12px 24px;
}

.size-lg {
  font-size: 1.0625rem;
  padding: 14px 32px;
}

.button.full {
  width: 100%;
}

/* Variants */
.variant-primary {
  background: var(--brand);
  color: var(--text-on-brand);
}

.variant-primary:hover {
  background: var(--brand-hover);
  box-shadow: var(--shadow-brand);
}

.variant-secondary {
  background: var(--secondary);
  color: var(--text-on-brand);
}

.variant-secondary:hover {
  background: var(--secondary-hover);
  box-shadow: var(--shadow-secondary);
}

.variant-outline {
  background: transparent;
  color: var(--brand);
  border: 1.5px solid var(--border-brand);
}

.variant-outline:hover {
  background: var(--sage-100);
  border-color: var(--brand);
}

.variant-ghost {
  background: transparent;
  color: var(--brand);
}

.variant-ghost:hover {
  background: var(--sage-50);
}

.variant-ink {
  background: var(--ink-900);
  color: var(--white);
}

.variant-ink:hover {
  background: var(--ink-800);
}
</style>

// design-system/ashish-portfolio-design-system/project/components/core/Button.jsx
import React from "react";

/**
 * Button — the primary call-to-action for the Ashish portfolio.
 * Soft, pill-shaped, calm motion. Variants map to brand roles.
 */
export function Button({
  children,
  variant = "primary",
  size = "md",
  as = "button",
  iconLeft = null,
  iconRight = null,
  full = false,
  disabled = false,
  style = {},
  ...rest
}) {
  const sizes = {
    sm: { padding: "8px 16px", fontSize: "0.875rem", gap: "6px" },
    md: { padding: "12px 24px", fontSize: "1rem", gap: "8px" },
    lg: { padding: "16px 32px", fontSize: "1.125rem", gap: "10px" },
  };

  const variants = {
    primary: {
      background: "var(--brand)",
      color: "var(--text-on-brand)",
      border: "none",
      boxShadow: "var(--shadow-brand)",
    },
    secondary: {
      background: "var(--peri-500)",
      color: "#fff",
      border: "none",
      boxShadow: "var(--shadow-peri)",
    },
    outline: {
      background: "transparent",
      color: "var(--brand-ink)",
      border: "2px solid var(--rose-300)",
      boxShadow: "none",
    },
    ghost: {
      background: "transparent",
      color: "var(--text-strong)",
      border: "2px solid transparent",
      boxShadow: "none",
    },
    ink: {
      background: "var(--plum-900)",
      color: "#fff",
      border: "none",
      boxShadow: "var(--shadow-md)",
    },
  };

  const Tag = as;
  return (
    <Tag
      disabled={as === "button" ? disabled : undefined}
      style={{
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: sizes[size].gap,
        width: full ? "100%" : "auto",
        padding: sizes[size].padding,
        fontSize: sizes[size].fontSize,
        fontFamily: "var(--font-sans)",
        fontWeight: 600,
        lineHeight: 1,
        letterSpacing: "-0.01em",
        borderRadius: "var(--radius-pill)",
        cursor: disabled ? "not-allowed" : "pointer",
        opacity: disabled ? 0.5 : 1,
        transition: "transform var(--dur-fast) var(--ease-soft), filter var(--dur-fast) var(--ease-soft), box-shadow var(--dur-base) var(--ease-soft)",
        textDecoration: "none",
        whiteSpace: "nowrap",
        ...variants[variant],
        ...style,
      }}
      onMouseDown={(e) => { if (!disabled) e.currentTarget.style.transform = "scale(0.97)"; }}
      onMouseUp={(e) => { e.currentTarget.style.transform = "scale(1)"; }}
      onMouseEnter={(e) => { if (!disabled) e.currentTarget.style.filter = "brightness(1.04)"; }}
      onMouseLeave={(e) => { e.currentTarget.style.filter = "none"; e.currentTarget.style.transform = "scale(1)"; }}
      {...rest}
    >
      {iconLeft}
      {children}
      {iconRight}
    </Tag>
  );
}
