// src/components/Badge.vue
<template>
  <span :class="['badge', `tone-${tone}`]">
    <slot></slot>
  </span>
</template>

<script setup>
defineProps({
  tone: { type: String, default: 'success' }, // success, warning, danger
})
</script>

<style scoped>
.badge {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 6px 14px;
  border-radius: var(--radius-pill);
  font-size: 0.8125rem;
  font-weight: 600;
  font-family: var(--font-sans);
}

.tone-success {
  background: rgba(78, 122, 74, 0.12);
  color: var(--leaf);
}

.tone-warning {
  background: rgba(194, 146, 47, 0.12);
  color: var(--amber);
}

.tone-danger {
  background: rgba(181, 80, 60, 0.12);
  color: var(--rust);
}
</style>

// design_system_extracted/ashish-portfolio-design-system/project/components/core/Badge.jsx
import React from "react";

/**
 * Badge — small status dot+label or count. Quieter than a Tag.
 */
export function Badge({ children, tone = "success", dot = true, style = {}, ...rest }) {
  const tones = {
    success: "var(--success)",
    warning: "var(--warning)",
    danger:  "var(--danger)",
    info:    "var(--secondary)",
    neutral: "var(--stone-500)",
  };
  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: "7px",
        fontFamily: "var(--font-sans)",
        fontSize: "0.8125rem",
        fontWeight: 600,
        color: "var(--text-body)",
        ...style,
      }}
      {...rest}
    >
      {dot && (
        <span
          style={{
            width: "8px",
            height: "8px",
            borderRadius: "999px",
            background: tones[tone],
            flex: "none",
          }}
        />
      )}
      {children}
    </span>
  );
}
