// src/components/Tag.vue
<template>
  <span :class="['tag', `tone-${tone}`]">
    <slot></slot>
  </span>
</template>

<script setup>
defineProps({
  tone: { type: String, default: 'sage' }, // sage, camel, clay, stone
})
</script>

<style scoped>
.tag {
  display: inline-flex;
  align-items: center;
  padding: 8px 14px;
  border-radius: var(--radius-pill);
  font-size: 0.875rem;
  font-weight: 500;
  font-family: var(--font-sans);
  border: 1px solid transparent;
}

.tone-sage {
  background: var(--sage-100);
  color: var(--sage-700);
  border-color: var(--sage-200);
}

.tone-camel {
  background: var(--camel-100);
  color: var(--camel-700);
  border-color: var(--camel-200);
}

.tone-clay {
  background: var(--clay-200);
  color: var(--clay-600);
  border-color: var(--clay-300);
}

.tone-stone {
  background: var(--stone-100);
  color: var(--stone-700);
  border-color: var(--stone-200);
}
</style>

// design_system_extracted/ashish-portfolio-design-system/project/components/core/Tag.jsx
import React from "react";

/**
 * Tag — soft pill label for skills, categories, filters.
 */
export function Tag({ children, tone = "sage", size = "md", style = {}, ...rest }) {
  const tones = {
    sage:  { bg: "var(--sage-100)",  fg: "var(--sage-700)" },
    camel: { bg: "var(--camel-100)", fg: "var(--camel-700)" },
    clay:  { bg: "var(--clay-200)",  fg: "var(--clay-600)" },
    stone: { bg: "var(--stone-100)", fg: "var(--stone-700)" },
    ink:   { bg: "var(--ink-900)",   fg: "var(--stone-50)" },
  };
  const sizes = {
    sm: { padding: "3px 10px", fontSize: "0.75rem" },
    md: { padding: "5px 14px", fontSize: "0.8125rem" },
  };
  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: "6px",
        fontFamily: "var(--font-sans)",
        fontWeight: 600,
        letterSpacing: "0.01em",
        borderRadius: "var(--radius-pill)",
        background: tones[tone].bg,
        color: tones[tone].fg,
        ...sizes[size],
        ...style,
      }}
      {...rest}
    >
      {children}
    </span>
  );
}
