// design-system/ashish-portfolio-design-system/project/components/forms/Textarea.jsx
import React from "react";

/**
 * Textarea — multi-line companion to Input.
 */
export function Textarea({ label = "", hint = "", rows = 4, id, style = {}, ...rest }) {
  const taId = id || (label ? label.toLowerCase().replace(/\s+/g, "-") : undefined);
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "6px", ...style }}>
      {label && (
        <label
          htmlFor={taId}
          style={{
            fontFamily: "var(--font-sans)",
            fontSize: "0.8125rem",
            fontWeight: 600,
            color: "var(--text-strong)",
          }}
        >
          {label}
        </label>
      )}
      <textarea
        id={taId}
        rows={rows}
        style={{
          fontFamily: "var(--font-sans)",
          fontSize: "1rem",
          color: "var(--text-strong)",
          padding: "12px 16px",
          background: "var(--surface-card)",
          border: "1.5px solid var(--border)",
          borderRadius: "var(--radius-md)",
          outline: "none",
          resize: "vertical",
          lineHeight: "1.5",
          transition: "border-color var(--dur-fast) var(--ease-soft), box-shadow var(--dur-fast) var(--ease-soft)",
          width: "100%",
        }}
        onFocus={(e) => {
          e.currentTarget.style.borderColor = "var(--focus-ring)";
          e.currentTarget.style.boxShadow = "0 0 0 3px var(--focus-ring-soft)";
        }}
        onBlur={(e) => {
          e.currentTarget.style.borderColor = "var(--border)";
          e.currentTarget.style.boxShadow = "none";
        }}
        {...rest}
      />
      {hint && <span style={{ fontSize: "0.75rem", color: "var(--text-muted)" }}>{hint}</span>}
    </div>
  );
}

// src/components/Textarea.vue
<template>
  <div class="textarea-group">
    <label v-if="label" :for="id" class="label">{{ label }}</label>
    <textarea
      :id="id"
      :placeholder="placeholder"
      :rows="rows"
      :value="modelValue"
      @input="$emit('update:modelValue', $event.target.value)"
      class="textarea"
    ></textarea>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  label: String,
  placeholder: String,
  rows: { type: Number, default: 3 },
  modelValue: String,
})

defineEmits(['update:modelValue'])

const id = computed(() => `textarea-${Math.random().toString(36).substr(2, 9)}`)
</script>

<style scoped>
.textarea-group {
  display: flex;
  flex-direction: column;
}

.label {
  font-family: var(--font-sans);
  font-size: 0.875rem;
  font-weight: 600;
  color: var(--text-strong);
  margin-bottom: 8px;
}

.textarea {
  padding: 12px 14px;
  border: 1px solid var(--border);
  border-radius: var(--radius-md);
  font-family: var(--font-sans);
  font-size: 1rem;
  color: var(--text-body);
  background: var(--white);
  resize: vertical;
  transition: border-color var(--dur-fast) var(--ease-soft), box-shadow var(--dur-fast) var(--ease-soft);
}

.textarea:focus {
  outline: none;
  border-color: var(--brand);
  box-shadow: 0 0 0 3px var(--focus-ring-soft);
}

.textarea::placeholder {
  color: var(--text-muted);
}
</style>
